version: '2'
services:
 namenode:
  image: bigtop-hadoop-master:ubuntu-15.04-x86_64
  container_name: "namenode"
  hostname: "namenode"
  ports:
    - "50070"
  command: "/etc/bigtop/start_bigtop_services.sh namenode resourcemanager -d"
  volumes:
    - .:/data
  privileged: true
 datanode:
  image: bigtop-hadoop-node:ubuntu-15.04-x86_64
  links:
    - "namenode"
  depends_on:
    - namenode 
  command: "/etc/bigtop/start_bigtop_services.sh datanode nodemanager -d"
  volumes:
   - .:/data
  privileged: true
 client:
  image: bigtop-hadoop-node:ubuntu-15.04-x86_64
  links:
    - "namenode"
    - "datanode"
  command: "/etc/bigtop/start_bigtop_services.sh -d"
  volumes:
   - .:/data
  privileged: true
