version: '2'
services:
 namenode:
  image: bigtop-hadoop-master:ubuntu-15.04-x86_64
  container_name: "namenode"
  hostname: "namenode"
  ports:
    - "50070"
  command: "/etc/bigtop/start_bigtop_services.sh namenode resourcemanager -d"
  volumes:
    - .:/data
  privileged: true
 datanode:
  image: bigtop-hadoop-worker:ubuntu-15.04-x86_64
  command: "/etc/bigtop/start_bigtop_services.sh datanode nodemanager 'spark-worker' -d"
  volumes:
   - .:/data
  privileged: true
 spark:
  image: bigtop-spark-master:ubuntu-15.04-x86_64
  container_name: "spark-master"
  depends_on:
    - "namenode"
    - "datanode"
  hostname: "spark-master"
  command: "/etc/bigtop/start_bigtop_services.sh 'spark-master' -d"
  volumes:
   - .:/data
  privileged: true
 zeppelin:
  image: bigtop-zeppelin:ubuntu-15.04-x86_64
  container_name: "zeppelin"
  depends_on:
    - "spark"
    - namenode
  hostname: "zeppelin"
  command: "/etc/bigtop/start_bigtop_services.sh 'zeppelin' -d"
  volumes:
   - .:/data
  privileged: true
